name: Deploy to AWS Lambda

on:
  push:
    branches: 
      - main

  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  LAMBDA_FUNCTION_NAME: prod-mightybyte-lambda
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pytest
        pip install boto3
        pip install sentry-sdk


    - name: Exporting Envs and Run tests
      run: |
        export DB_HOST=${{ vars.DB_HOST }}
        export DB_NAME=${{ vars.DB_NAME }}
        export REGION=${{ vars.REGION}}
        export SECRET_NAME=${{ vars.SECRET_NAME }}
        export SENTRY_DSN=${{ vars.SENTRY_DSN }}
        pytest tests/lambda_test.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Making Zip of the code with package
      id: zipping
      run: |
        rm -rf lambda_function 
        mkdir lambda_function
        cp lambda_function.py lambda_function/
        cd lambda_function
        pip3 install sentry-sdk -t .
        ls
        zip -r ../lambda_function.zip .
        cd ..

    - name: Uploading that to lambda
      id: Uploading
      run: |
        aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://lambda_function.zip
