name: Deploy to AWS Lmmbda

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-west-2
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: Making Zip of the code with package
      id: zipping
      
      run: |
        rm -rf lambda_function 
        mkdir lambda_function
        cp lambda_function.py lambda_function/
        cd lambda_function
        pip3 install sentry-sdk -t .
        ls
        zip -r ../lambda_function.zip .
        cd ..

    - name: Uploading that to lambda
      id: Uploading
      
      run: |
        aws lambda update-function-code --function-name todo --zip-file fileb://lambda_function.zip

    

